// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBdbduHb9l5osk52CgYh5wqp8ef9Hg4Y',
    appId: '1:66815410352:web:05172f826d4baba952fb75',
    messagingSenderId: '66815410352',
    projectId: 'campus-share-6accf',
    authDomain: 'campus-share-6accf.firebaseapp.com',
    storageBucket: 'campus-share-6accf.firebasestorage.app',
    measurementId: 'G-M20625SV31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6HywB1d98nyN5HbO3pqVVC36_vh8LJI',
    appId: '1:66815410352:android:9d6da9e01d9a5d9052fb75',
    messagingSenderId: '66815410352',
    projectId: 'campus-share-6accf',
    storageBucket: 'campus-share-6accf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy7V3R-cjxmyBON6BGemDjtwSXMyXrUBE',
    appId: '1:66815410352:ios:47bebae98c78431752fb75',
    messagingSenderId: '66815410352',
    projectId: 'campus-share-6accf',
    storageBucket: 'campus-share-6accf.firebasestorage.app',
    iosBundleId: 'com.example.sharingplatform.sharingplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy7V3R-cjxmyBON6BGemDjtwSXMyXrUBE',
    appId: '1:66815410352:ios:47bebae98c78431752fb75',
    messagingSenderId: '66815410352',
    projectId: 'campus-share-6accf',
    storageBucket: 'campus-share-6accf.firebasestorage.app',
    iosBundleId: 'com.example.sharingplatform.sharingplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBBdbduHb9l5osk52CgYh5wqp8ef9Hg4Y',
    appId: '1:66815410352:web:0f8b0fe1838920aa52fb75',
    messagingSenderId: '66815410352',
    projectId: 'campus-share-6accf',
    authDomain: 'campus-share-6accf.firebaseapp.com',
    storageBucket: 'campus-share-6accf.firebasestorage.app',
    measurementId: 'G-SHHSD5TBTB',
  );
}
